### ISSUE TITLE
plugin fails when revengStrategy used

### ISSUE THREAD

**Issue by thejonamreddy** [stadler/hibernate-tools-maven-plugin-sample#2]
Hi,

When the `revengStrategy` is used, the plugin fails with the following error
`Failed to execute goal org.hibernate:hibernate-tools-maven-plugin:5.4.20.Final:hbm2java (default-cli) on project hibernate-tools-demo: Execution default-cli of goal org.hibernate:hibernate-tools-maven-plugin:5.4.20.Final:hbm2java failed: com.jonamlabs.hibernatetoolsdemo.CustomReverseEngineeringStrategy not instanced. -> [Help 1] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.hibernate:hibernate-tools-maven-plugin:5.4.20.Final:hbm2java (default-cli) on project hibernate-tools-demo: Execution default-cli of goal org.hibernate:hibernate-tools-maven-plugin:5.4.20.Final:hbm2java failed: com.jonamlabs.hibernatetoolsdemo.CustomReverseEngineeringStrategy not instanced.`

**Comment by stadler** [comment]
Hi
Please reports bugs of the plugin to the [hibernate-tools](https://github.com/hibernate/hibernate-tools/tree/master/maven) project as it has been integrated there. Thanks!
